sudo: required
language: rust
cache: cargo

# necessary for `cargo coveralls`
addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly

matrix:
  fast_finish: true

# load travis-cargo
before_script:
  - |
      export PATH=$HOME/.local/bin:$PATH
      cargo install cargo-update || echo "cargo-update already installed" &&
      cargo install cargo-travis || echo "cargo-travis already installed" &&
      cargo install-update -a

script:
  - |
      cargo install diesel_cli --no-default-features --features sqlite --force &&
      diesel migration run &&
      cargo build &&
      cargo test

after_success:
  - cargo coveralls
