[package]
name = "openfairdb"
version = "0.3.4-dev"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]

[dependencies]
clap = "2"
log = "0.4"
env_logger = "0.5"
uuid = { version = "0.6", features = ["v4"] }
url = "1"
quick-error = "1"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1"
serde_json = "1"
serde_derive = "1"
chrono = "0.4"
lazy_static = "1"
regex = "0.2"
pwhash = "0.1"
fast_chemail = "0.9"
quoted_printable = "0.4"
toml = "0.4"
dotenv = "0.11"
diesel = { version = "1", features = ["sqlite", "large-tables", "r2d2"] }
diesel_migrations = { version = "1", features = ["sqlite"]  }
libsqlite3-sys = { version = "0.9", features = ["bundled"] }

[features]
default = ["email"]
email = []
